version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/simple-python-deploy/

hooks:
  ApplicationStop:
    - location: scripts/stop_container.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 300
      runas: ubuntu
